name: todo_list_1
description: A Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.5
  sqflite: ^1.3.0
  path: ^1.6.4

  pedantic: ^1.9.0
  #lint

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
